table _Metrics
	lineageTag: 38e10cb0-3089-491d-bf5f-17d7fc52a660

	measure KPI = [KPI Measure]
		displayFolder: _Measures
		lineageTag: b658f670-5f1f-4a17-bdb9-4b42d932de45

		kpi
			targetExpression = [KPI PY]
			targetFormatString: $ #,##0.00
			statusGraphic: Road Signs
			statusExpression =
				VAR _tolerance = 0.01
				VAR _direction =
				    IF ( SELECTEDVALUE ( _Metrics[Favorable Positive] ) = TRUE (), 1, -1 )
				VAR _value = [KPI]
				VAR _prev = [KPI PY]
				VAR _ratio =
				    _direction * DIVIDE ( _value - _prev, _prev )
				RETURN
				    IF (
				        NOT ISBLANK ( _value ) && NOT ISBLANK ( _prev ),
				        SWITCH ( TRUE (), _ratio > _tolerance, 1, _ratio < - _tolerance, -1, 0 )
				    )
			trendGraphic: Standard Arrow
			trendExpression =
				VAR _tolerance = 0.01
				VAR _direction =
				    IF ( SELECTEDVALUE ( _Metrics[Favorable Positive] ) = TRUE (), 1, -1 )
				VAR _value = [KPI]
				VAR _prev =
				    CALCULATE ( [KPI], DATEADD ( 'Calendar'[Date], -1, MONTH ) )
				VAR _ratio =
				    _direction * DIVIDE ( _value - _prev, _prev )
				RETURN
				    IF (
				        NOT ISBLANK ( _value ) && NOT ISBLANK ( _prev ),
				        SWITCH ( TRUE (), _ratio > _tolerance, 1, _ratio < - _tolerance, -1, 0 )
				    )

		formatStringDefinition = COALESCE( SELECTEDVALUE( _Metrics[Format String] ), FIRSTNONBLANK( _Metrics[Format String] , 0 ) )

	measure 'KPI PY' =
			
			VAR _year =
			    SELECTEDVALUE ( 'Calendar'[Year] )
			RETURN
			    IF (
			        NOT ISBLANK ( _year ),
			        CALCULATE ( [KPI Measure], DATEADD ( 'Calendar'[Date], -1, YEAR ) )
			    )
		displayFolder: _Measures
		lineageTag: 466518d5-5000-4b97-9c24-0b8fbfa61234

		formatStringDefinition = SELECTEDVALUE( _Metrics[Format String] )

	measure 'KPI Metric Title' =
			
			IF( ISFILTERED( _Metrics[Metric] ) || ISFILTERED( _Metrics[Metric Formatted] ),
			SELECTEDVALUE ( _Metrics[Metric] ),
			"Please select a metric or category"
			)
		displayFolder: Cosmetic
		lineageTag: 48154fa8-0fc3-43a5-accc-fc22c4706f13

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Metric Description' = IF ( HASONEVALUE ( _Metrics[Metric] ), SELECTEDVALUE ( _Metrics[Description] ) )
		displayFolder: Cosmetic
		lineageTag: c36033eb-b032-44f5-aae5-b5f36a10fbea

		annotation PBI_FormatHint = {"isText":true}

	measure 'KPI (Favorable )' =
			
			VAR _measure = [KPI Measure]
			VAR _direction = IF ( SELECTEDVALUE ( _Metrics[Favorable Positive] ) = TRUE (), 1, -1 )
			RETURN IF( NOT ISBLANK( _measure ), _measure * _direction )
		displayFolder: _Measures
		lineageTag: 29bbbb16-ed33-4c69-8fe4-d9350ca52595

		formatStringDefinition = SELECTEDVALUE( _Metrics[Format String] )

	measure 'KPI PY (Favorable)' =
			
			[KPI PY]
			    * IF ( SELECTEDVALUE ( _Metrics[Favorable Positive] ) = TRUE (), 1, -1 )
		displayFolder: _Measures
		lineageTag: 1b7da76d-94fb-45d7-b06a-c07d39911f28

		formatStringDefinition = SELECTEDVALUE( _Metrics[Format String] )

	measure 'KPI Measure' = ```
			
			SWITCH (
			    SELECTEDVALUE( _Metrics[Metric] ),
			    "REVENUE", InvoiceDate ( [Total Sales] ) + [Revenue Accrued], 
			    "Sales", InvoiceDate ( [Total Sales] ),
			    "Rev Accrual", [Revenue Accrued],
			    "COGS", ShipDate ( [Production Costs] ) + DeliverDate ( [Shipping Costs] ),
			    "Production Costs", ShipDate ( [Production Costs] ),
			    "Shipping Costs", DeliverDate ( [Shipping Costs] ),
			    "GROSS PROFIT",                             InvoiceDate ( [Total Sales] ) + [Revenue Accrued]
			            - ShipDate ( [Production Costs] )
			            - DeliverDate ( [Shipping Costs] ),
			    "Gross Margin", [Gross Margin],
			    "OPEX", [SG&A] + [Marketing Costs] + [Depreciation],
			    "SG&A", [SG&A],
			    "Marketing", [Marketing Costs],
			    "Depreciation", [Depreciation],
			    "OPERATING PROFIT", [EBIT],
			    "EBIT%", [EBIT %]
			)
			```
		displayFolder: _Measures
		lineageTag: 49feee0b-622f-404f-bc65-bed2301c3c96

		formatStringDefinition = SELECTEDVALUE( _Metrics[Format String] )

	measure 'KPI Visuals' =
			
			IF( ISFILTERED( _Metrics[Metric Formatted] ), [KPI] )
		displayFolder: Cosmetic
		lineageTag: ad86707a-1e1e-43fd-b66c-cd9e99584c79

		formatStringDefinition = COALESCE( SELECTEDVALUE( _Metrics[Format String] ), FIRSTNONBLANK( _Metrics[Format String] , 0 ) )

	measure 'KPI Chg PY' =
			
			VAR _kpi = [KPI (Favorable )]
			VAR _kpipy = [KPI PY (Favorable)]
			RETURN IF( NOT ISBLANK( _kpi ) && NOT ISBLANK( _kpipy ), _kpi - _kpipy )
		displayFolder: _Measures
		lineageTag: 84537e9b-1b44-40bd-96b3-2bbbd01511a8

		formatStringDefinition = SELECTEDVALUE( _Metrics[Format String] )

	measure 'KPI Metric Chg PY Title' =
			
			VAR _title = [KPI Metric Title]
			RETURN _title & " Chg from PY"
		displayFolder: Cosmetic
		lineageTag: 97069ef0-803e-4daa-8fe8-7785386bd6f9

		annotation PBI_FormatHint = {"isText":true}

	column Metric
		dataType: string
		lineageTag: 31180668-e663-41ff-8078-8400030126e3
		summarizeBy: none
		sourceColumn: Metric
		sortByColumn: Metric_Ordinal

		changedProperty = SortByColumn

		annotation SummarizationSetBy = Automatic

	column Units
		dataType: string
		isHidden
		lineageTag: f65fa8a8-d34a-4967-ba8c-621a0c5a7864
		summarizeBy: none
		sourceColumn: Units

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column Summary
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: bef367d5-0bc7-4200-b592-e5fc630f7e49
		summarizeBy: none
		sourceColumn: Summary

		annotation SummarizationSetBy = Automatic

	column 'Favorable Positive'
		dataType: boolean
		isHidden
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: ef351db7-a61f-44b9-bfe0-1308ee04cc32
		summarizeBy: none
		sourceColumn: Favorable Positive

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column Description
		dataType: string
		isHidden
		lineageTag: 1307bab9-3435-49fa-bc09-d4b882ed0815
		summarizeBy: none
		sourceColumn: Description

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column Metric_Ordinal
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: 1f9b501a-c2f0-4029-baff-137947a830c8
		summarizeBy: sum
		sourceColumn: Metric_Ordinal

		changedProperty = SortByColumn

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'Format String'
		dataType: string
		isHidden
		lineageTag: 90ef10ed-dc36-472d-8f1c-33890e265107
		summarizeBy: none
		sourceColumn: Format String

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'Metric Formatted'
		dataType: string
		lineageTag: 34b994aa-fa0d-4f85-b0fd-c6b2ec763271
		summarizeBy: none
		sourceColumn: Metric Formatted
		sortByColumn: Metric_Ordinal

		changedProperty = SortByColumn

		annotation SummarizationSetBy = Automatic

	partition _Metrics = m
		mode: import
		source =
				let
				    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText("fZBND4IwDIb/yrKEmybGg3fUuXAQyIbGBDksuOAiYWQDf7/zY8oQuKztk77t+qYpJOiIwgOCs052oFvzJqrlvwCzWQopK7k2BQBzAGzx7t6xUvfbCb8DP89Vy0orctG4dBNhavJPcD5k2199sZKXNm+ErMBG6ub7uQHuLnOm0Kuoa1EV7ow/OjEBk4hSEJNoFySG9cpRQ7GSWoM9U4Wo7Noe84aVUYxOJv+EcYMoPreLxXLlf6/qgImDzP4bb8z1VtcFE7otrxXPBXtab6U9NqE25xA/CUL8824AjdqJ1kHi2a22GDIwewA=", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [Metric = _t, #"Metric Formatted" = _t, Units = _t, Summary = _t, #"Favorable Positive" = _t, Description = _t]),
				    #"Changed Type" = Table.TransformColumnTypes(Source,{{"Summary", type logical}, {"Favorable Positive", type logical}}),
				    #"Added Index" = Table.AddIndexColumn(#"Changed Type", "Metric_Ordinal", 1, 1, Int64.Type),
				    #"Merged Queries" = Table.NestedJoin(#"Added Index", {"Units"}, format_metrics, {"Units"}, "format_metrics", JoinKind.LeftOuter),
				    #"Expanded format_metrics" = Table.ExpandTableColumn(#"Merged Queries", "format_metrics", {"Format String"}, {"Format String"})
				in
				    #"Expanded format_metrics"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

