table _PM
	lineageTag: ec8cc4c9-8629-49c9-9199-adc0f2c6970a

	column Metric
		dataType: string
		lineageTag: 7e0d67b6-5d6c-46d1-9b8d-1905bdc12e9d
		summarizeBy: none
		sourceColumn: Metric
		sortByColumn: Metric_Ordinal

		changedProperty = SortByColumn

		annotation SummarizationSetBy = Automatic

	column Metric_Ordinal
		dataType: int64
		formatString: 0
		lineageTag: 0858a1b8-7941-4578-ba98-a051c7f0e24a
		summarizeBy: sum
		sourceColumn: Metric_Ordinal

		annotation SummarizationSetBy = Automatic

	partition _PM = m
		mode: import
		source =
				let
				    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText("i45WCk7MSS1W0lEyVIrVgfIU/AsK8otKSvMySyqBMkZgGfei/OJihYCi/LTMEqCgsVJsLAA=", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [Metric = _t, Metric_Ordinal = _t]),
				    #"Changed Type" = Table.TransformColumnTypes(Source,{{"Metric", type text}, {"Metric_Ordinal", Int64.Type}})
				in
				    #"Changed Type"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

