table DIM_Factories
	lineageTag: 45fa2bb0-0d46-407f-8527-fca7afe32aa8

	column Factory
		dataType: string
		lineageTag: 46f1133f-ba5f-41af-a676-37f43d3671fb
		summarizeBy: none
		sourceColumn: Factory

		annotation SummarizationSetBy = Automatic

	column Latitude
		dataType: double
		lineageTag: 91c60bda-e769-4636-8eb4-4c2ed2db619b
		summarizeBy: none
		sourceColumn: Latitude

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Longitude
		dataType: double
		lineageTag: 8a721b86-9e88-437c-975f-c324b6a295e7
		summarizeBy: none
		sourceColumn: Longitude

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	partition DIM_Factories = m
		mode: import
		source =
				let
				    Source = source_tables,
				    #"Filtered Rows" = Table.SelectRows(Source, each [Table] = "Candy_Factories"),
				    Table = #"Filtered Rows"{0}[Table],
				    URL = pDataFileLocation & Table & ".csv",
				    URLContents = Web.Contents(URL),
				    CSVExtract = Csv.Document(URLContents),
				    #"Promoted Headers" = Table.PromoteHeaders(CSVExtract, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"Latitude", type number}, {"Longitude", type number}})
				in
				    #"Changed Type"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

